name: Build Branch

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@master
    - name: MSBuild
      run: |
        $sha = $env:GITHUB_SHA.substring(0,7)
        msbuild /t:BH:Rebuild /p:Configuration=Release /p:CustomDefinitions="SHA="$sha" BH.sln
    - uses: actions/upload-artifact@v4
      with:
        name: BH.dll
        path: Release/BH.dll